// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"bbcsyncer/infra"
	"bbcsyncer/sync"
)

// Injectors from wire.go:

func InitializeWorker() (*sync.Worker, error) {
	conf := infra.ParseConf()
	db, err := infra.NewPGDB(conf)
	if err != nil {
		return nil, err
	}
	repo := sync.NewRepo(db)
	client, err := infra.NewBBCClient(conf)
	if err != nil {
		return nil, err
	}
	worker := sync.NewWorker(repo, client)
	return worker, nil
}
