// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"bbcsyncer/infra"
	"bbcsyncer/reward"
	"bbcsyncer/sync"
)

// Injectors from wire.go:

func Initialize() (*reward.Calc, error) {
	conf := infra.ParseConf()
	db, err := infra.NewPGDB(conf)
	if err != nil {
		return nil, err
	}
	repo := reward.NewRepo(db)
	syncRepo := sync.NewRepo(db)
	calc := reward.NewCalc(repo, syncRepo)
	return calc, nil
}
